//! M10 T5.1 — the scripted sessions every M9 knob was waiting for.
//!
//! M9 shipped five knobs at their defaults and could not read four of them,
//! for one reason: *the scripted suite carries no summary and no notes*. Its
//! §Results T0.4 says so in the only way that matters — `--ablate summary`
//! and `--ablate guidance` both reported **9/9 → 9/9**, a zero that means
//! "nothing to see" rather than "nothing there". A blind instrument and an
//! insensitive one print the same number.
//!
//! So this module builds sessions that demonstrably carry both, out of
//! **hand-authored seeds**. Not a generator model: the plan's own risk line
//! is *"fixtures generated by a model leak the model's style"*, and the
//! answer it wrote down is a seed a person can read, a deterministic
//! expansion, and a byte-identical regeneration ([`render_corpus`], graded by
//! `fixtures_regenerate_byte_identically`).
//!
//! # What one session carries
//!
//! Every seed expands to the same twelve-turn shape, because the shape is
//! what makes the ablation arms readable — a suite whose fixtures carried a
//! summary *sometimes* would produce a delta nobody could attribute.
//!
//! | turn | what happens | which exit criterion it serves |
//! |---|---|---|
//! | 1 | the **opening**: said once, never remembered as a fact | (a) only the rolling summary can carry its `mark` into turn 11 |
//! | 2 | the durable statement → `remember_fact` | (d) the graded question paraphrases *this* sentence |
//! | 3 | the same key **restated with a new value** | (c) LongMemEval's knowledge update; graded on the new value |
//! | 4–10 | filler, which pushes turns 1–3 out of the six-turn window | the window cannot be the source of the answer |
//! | 11 | the graded question — a paraphrase, cs or en | (d) |
//! | 12 | a question about something the session never held | (e) abstention, scored in its own arm |
//!
//! `maybe_summarize` runs after every turn, exactly where `dispatch.rs` runs
//! it on the live path. With `window_turns = 6` and `summary_every_turns = 4`
//! that fires once, after turn 10, over turns 1–4 — so turn 11's reply
//! context carries a real `Summarized` event built by the engine's own
//! summarizer path, and the `mark` from turn 1 is in the prompt through the
//! summary block and through nothing else.
//!
//! Notes arrive the way the live engine gets them, through
//! [`nscore::LearnedRules`] on `EngineConfig.learned`. **Two of them are
//! scoped `reply`, one `global`**, and that split is not decoration:
//! `guidance_notes_for_reply` (`crates/core/src/learned.rs`) renders only
//! `reply`-scoped notes into the reply context, and the graded turn is a
//! reply turn. A fixture that handed the engine two `global` notes and then
//! graded the reply prompt would have been blind in a new way.
//!
//! # Why abstention is a separate arm
//!
//! 2606.09376: precision-only scoring rewards a model that answers nothing.
//! If the unanswerable items were folded into one pass rate, a harness that
//! declined every question would climb it. So [`Fixture`] carries `passed`
//! and `declined` as two verdicts over two turns, [`render_table`] prints
//! two totals, and neither can be bought with the other.
//!
//! # What the table prints that the M9 one could not
//!
//! `summary` and `notes` per fixture, read off the **store and the rules**
//! rather than off the graded context. Under `--ablate summary` the block is
//! blanked after the fit, so the graded turn sees none — but the session
//! still holds its `Summarized` event, and the column says so. That is the
//! difference between blind and insensitive, printed rather than argued.

use crate::eval::{recall_for, remember, require, Harness, Run, Shown};
use nscore::{EventKind, FactState, LearnedRules, MemoryStore, Note, Proposal, SessionId};

// ---------------------------------------------------------------------------
// The seed
// ---------------------------------------------------------------------------

/// One hand-authored session: a persona, a timeline and the two questions it
/// is graded on.
///
/// Every field is a literal somebody wrote and can argue with. The expansion
/// in [`generate`] adds nothing that is not derivable from these fields plus
/// the filler pool, which is what makes regeneration byte-identical.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Seed {
    pub id: &'static str,
    /// Which of the six memory abilities this session belongs to. Five seeds
    /// each; `every_memory_ability_has_at_least_five_sessions` is the guard.
    pub ability: &'static str,
    /// "cs" or "en". Both, for `paraphrase.rs`'s reason: this deployment's
    /// traffic is Czech and Czech inflects the tokens a lexical index keys on.
    pub lang: &'static str,
    pub persona: &'static str,
    /// Turn 1. Said once and never written as a fact, so the only route from
    /// it to turn 11 is the rolling summary.
    pub opening: &'static str,
    /// A word of `opening` that appears nowhere else in the session — the
    /// token the summary condition looks for.
    pub mark: &'static str,
    /// Turn 2: the sentence `ask` paraphrases, and the fact it writes.
    pub said: &'static str,
    pub key: &'static str,
    pub value: &'static str,
    /// Turn 3: the same key with a new value. The graded answer is the new
    /// one; the old one is legitimate material only behind the `(was …)`
    /// marker.
    pub updated: &'static str,
    pub update_new: &'static str,
    /// Turn 11, in different words from `said` — graded by
    /// `every_graded_question_is_a_paraphrase`.
    pub ask: &'static str,
    /// The session's own `reply`-scoped note, beside the ability's.
    pub note: &'static str,
    /// Turn 12: a question this session never held an answer to.
    pub unanswerable: &'static str,
    /// A span of `unanswerable` whose tokens appear nowhere in the session,
    /// so `recall` can only report "no matches".
    pub recall_query: &'static str,
    /// What a reply that did not decline would have to invent.
    pub invented: &'static str,
    /// A first draft that states it, so the grounding interceptor — harness,
    /// not model — is what the abstention arm grades.
    pub invented_draft: &'static str,
}

/// The six memory abilities, in the order [`crate::eval::run_all_for`]
/// reports them. Written down so the ability column of this table and the
/// ability column of that one cannot drift apart.
pub const MEMORY_ABILITIES: [&str; 6] = [
    "information extraction",
    "multi-session reasoning",
    "temporal reasoning",
    "knowledge updates",
    "abstention",
    "selective forgetting",
];

/// The note every session carries at `global` scope: it reaches the emitter,
/// which is the half of the engine `guidance_notes_for` serves.
pub const GLOBAL_NOTE: &str = "Prefer a stored fact over asking the user again.";

/// One `reply`-scoped note per ability, the thing that ability's graded turn
/// is supposed to act on.
pub fn ability_note(ability: &str) -> &'static str {
    match ability {
        "information extraction" => "Answer from the stored facts, not from the transcript.",
        "multi-session reasoning" => "A fact stated in another conversation still counts.",
        "temporal reasoning" => "When a value changed, give the current one and name the old one.",
        "knowledge updates" => "Only the newest value of a key is true.",
        "abstention" => "If the context does not carry it, say you do not know.",
        _ => "A forgotten value is gone; do not reconstruct it.",
    }
}

/// Filler, one pool per language. Deliberately contentless: its whole job is
/// to push turns 1–3 out of the six-turn window, and a filler line that said
/// anything would become a second source for the graded answer.
const EN_FILLER: [&str; 8] = [
    "what else can you do",
    "never mind that",
    "tell me something",
    "still there?",
    "good",
    "carry on",
    "one more thing",
    "right",
];

const CS_FILLER: [&str; 8] = [
    "co ještě umíš",
    "to nech být",
    "řekni mi něco",
    "jsi tam?",
    "dobře",
    "pokračuj",
    "ještě něco",
    "tak jo",
];

/// Seven filler lines for the `n`th seed, rotated through the pool so two
/// sessions do not read identically. A pure function of `(lang, n)`, which is
/// what keeps regeneration byte-identical.
fn filler(lang: &str, n: usize) -> Vec<&'static str> {
    let pool: &[&'static str; 8] = if lang == "cs" { &CS_FILLER } else { &EN_FILLER };
    (0..7).map(|i| pool[(n + i) % pool.len()]).collect()
}

/// "forget this" and "and now?", per language — the two extra turns the
/// selective-forgetting seeds take.
fn forget_turns(lang: &str) -> (&'static str, &'static str) {
    if lang == "cs" {
        ("zapomeň to prosím", "a co to bylo?")
    } else {
        ("please forget that", "and what was it?")
    }
}

/// The one line the multi-session seeds say in a second session.
fn second_session_ask(lang: &str) -> &'static str {
    if lang == "cs" {
        "připomeň mi to ještě jednou"
    } else {
        "remind me of that once more"
    }
}

// ---------------------------------------------------------------------------
// The generated session
// ---------------------------------------------------------------------------

/// What a turn is for, so the runner and the renderer read the same plan
/// instead of each counting turns for themselves.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Role {
    /// Turns 1–3 and the filler: they build the state, they are not graded.
    Setup,
    /// Turn 11 — the paraphrased question the answerable arm grades.
    Graded,
    /// Turn 12 — the unanswerable one, graded in its own arm.
    Abstain,
    /// Selective forgetting: the request, then the question after it.
    Forget,
    Recheck,
    /// Multi-session: the same question in a second session.
    Across,
}

/// One turn of a generated session.
#[derive(Debug, Clone, PartialEq)]
pub struct Turn {
    pub text: String,
    pub script: Vec<Proposal>,
    pub role: Role,
    /// `false` for the session the seed is about, `true` for the second one
    /// the multi-session seeds open.
    pub second_session: bool,
    /// The inventing first draft, on the abstention turn only.
    pub first_draft: Option<&'static str>,
}

/// A seed expanded into the turns a harness can run.
#[derive(Debug, Clone, PartialEq)]
pub struct Session {
    pub seed: Seed,
    pub notes: Vec<Note>,
    pub turns: Vec<Turn>,
}

impl Session {
    /// Notes the reply model can be shown — the `reply`-scoped ones, which
    /// is what `guidance_notes_for_reply` filters to.
    pub fn reply_notes(&self) -> Vec<&str> {
        self.notes
            .iter()
            .filter(|n| n.scope == "reply")
            .map(|n| n.text.as_str())
            .collect()
    }

    pub fn rules(&self) -> LearnedRules {
        LearnedRules {
            notes: self.notes.clone(),
            ..LearnedRules::default()
        }
    }
}

fn plain(text: &str, role: Role) -> Turn {
    Turn {
        text: text.to_string(),
        script: vec![],
        role,
        second_session: false,
        first_draft: None,
    }
}

/// Expand every seed. Pure: same seeds and the same filler pool in, the same
/// `Vec<Session>` out, which is the whole of what
/// `fixtures_regenerate_byte_identically` checks.
pub fn generate() -> Vec<Session> {
    seeds()
        .iter()
        .enumerate()
        .map(|(n, seed)| {
            let mut turns = vec![
                plain(seed.opening, Role::Setup),
                Turn {
                    script: vec![remember(seed.key, seed.value)],
                    ..plain(seed.said, Role::Setup)
                },
                Turn {
                    script: vec![remember(seed.key, seed.update_new)],
                    ..plain(seed.updated, Role::Setup)
                },
            ];
            turns.extend(
                filler(seed.lang, n)
                    .into_iter()
                    .map(|t| plain(t, Role::Setup)),
            );
            turns.push(plain(seed.ask, Role::Graded));
            turns.push(Turn {
                script: vec![recall_for(seed.recall_query)],
                first_draft: Some(seed.invented_draft),
                ..plain(seed.unanswerable, Role::Abstain)
            });
            match seed.ability {
                "selective forgetting" => {
                    let (drop, again) = forget_turns(seed.lang);
                    turns.push(Turn {
                        script: vec![crate::eval::forget(seed.key)],
                        ..plain(drop, Role::Forget)
                    });
                    turns.push(plain(again, Role::Recheck));
                }
                "multi-session reasoning" => turns.push(Turn {
                    second_session: true,
                    ..plain(second_session_ask(seed.lang), Role::Across)
                }),
                _ => {}
            }
            Session {
                seed: *seed,
                notes: vec![
                    Note::new("reply", ability_note(seed.ability), 0.0),
                    Note::new("reply", seed.note, 0.0),
                    Note::new("global", GLOBAL_NOTE, 0.0),
                ],
                turns,
            }
        })
        .collect()
}

/// The whole corpus as one document, byte for byte.
///
/// The regeneration test needs something to compare, and comparing
/// `Vec<Session>` by `PartialEq` would pass on two structurally equal values
/// whose *rendering* differed — and the rendering is what a person reviews.
/// So the test compares this.
pub fn render_corpus() -> String {
    let mut out = String::from("M10 T5.1 — scripted sessions from hand-authored seeds\n");
    for s in generate() {
        out.push_str(&format!(
            "\n=== {} [{} · {}] ===\npersona: {}\n",
            s.seed.id, s.seed.ability, s.seed.lang, s.seed.persona
        ));
        for n in &s.notes {
            out.push_str(&format!("note[{}] {} {}\n", n.scope, n.hash, n.text));
        }
        for (i, t) in s.turns.iter().enumerate() {
            out.push_str(&format!(
                "{:>3} {:?}{} {}\n",
                i + 1,
                t.role,
                if t.second_session { " (session B)" } else { "" },
                t.text
            ));
            for p in &t.script {
                out.push_str(&format!("      -> {} {}\n", p.action, p.args));
            }
            if let Some(d) = t.first_draft {
                out.push_str(&format!("      ~~ first draft: {d}\n"));
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Running one session
// ---------------------------------------------------------------------------

/// One graded session: two verdicts, and the two counts that make a zero
/// delta readable.
#[derive(Debug, Clone, PartialEq)]
pub struct Fixture {
    pub id: &'static str,
    pub ability: &'static str,
    pub lang: &'static str,
    /// The answerable turn.
    pub passed: bool,
    /// The unanswerable one, in its own arm.
    pub declined: bool,
    pub turns: usize,
    pub requests: usize,
    /// Replier calls alone, both sessions of this fixture (M10 T5.4, arm 3).
    ///
    /// Split out of `requests` because the obligation interceptor's whole
    /// cost is a *second* replier call on a turn that already had one: an
    /// arm reported on `requests` would hide that regeneration among the
    /// emitter's proposals, which the knob does not touch.
    pub replier_requests: usize,
    pub prompt_chars: usize,
    /// Characters of `Summarized` this session **holds**, read off the event
    /// log. Non-zero even under `--ablate summary`, which is the point: a
    /// suite that reported zero here would be blind, and one that reported a
    /// number here and no delta is insensitive.
    pub summary_chars: usize,
    /// Characters of summary the graded turn was **shown**. Zero under
    /// `--ablate summary`.
    pub summary_shown: usize,
    /// `reply`-scoped notes handed to the engine, and the ones the graded
    /// context carried. Same pair of readings, same reason.
    pub notes_held: usize,
    pub notes_shown: usize,
    /// `ReplyEchoed` events this fixture's two sessions hold (M12 T4.4b).
    ///
    /// Reported per arm because the act-or-answer arm is the first one that
    /// changes *who writes the reply*: the double's fixed marker cannot echo
    /// its own prompt, and a model's answer can. A column that stays zero on
    /// both arms says the monitor saw nothing, not that nothing was there.
    pub echoed: usize,
    pub detail: String,
    pub abstain_detail: String,
}

/// `ReplyEchoed` events these sessions hold (M12 T4.4b).
async fn echoed_in(h: &Harness, sids: &[&SessionId]) -> usize {
    let mut n = 0;
    for sid in sids {
        n += h
            .store()
            .load(sid)
            .await
            .unwrap_or_default()
            .iter()
            .filter(|e| matches!(e.kind, EventKind::ReplyEchoed { .. }))
            .count();
    }
    n
}

/// The engine's own summary for this session, as the log holds it.
async fn summary_chars_of(h: &Harness, sid: &SessionId) -> usize {
    h.store()
        .load(sid)
        .await
        .unwrap_or_default()
        .iter()
        .filter_map(|e| match &e.kind {
            EventKind::Summarized { summary } => {
                Some(nscore::render_summary(summary).chars().count())
            }
            _ => None,
        })
        // The newest summary, found from the back: `last()` walked every
        // event in the session to arrive at the same one.
        .next_back()
        .unwrap_or(0)
}

/// Run one session and grade both of its arms.
pub async fn run_one(session: &Session, run: Run) -> Fixture {
    let seed = session.seed;
    let h = Harness::for_fixture(run, session.rules(), seed.persona);
    let a = SessionId(format!("fx-{}-a", seed.id.replace('/', "-")));
    let b = SessionId(format!("fx-{}-b", seed.id.replace('/', "-")));

    let mut graded: Option<Shown> = None;
    let mut abstain: Vec<Shown> = Vec::new();
    let mut recheck: Option<Shown> = None;
    let mut across: Option<Shown> = None;
    // Every version of the graded key **as the graded turn left it**. Read
    // inside the loop, not after it: the selective-forgetting seeds go on to
    // delete the key, and a history read at the end would grade the update
    // against a store the forget had already emptied.
    let mut history = Vec::new();
    for t in &session.turns {
        let sid = if t.second_session { &b } else { &a };
        let shown = h
            .turn_drafting(sid, &t.text, t.script.clone(), t.first_draft)
            .await;
        match t.role {
            Role::Graded => {
                graded = shown.first().cloned();
                history = h
                    .store()
                    .fact_history("global", seed.key)
                    .await
                    .unwrap_or_default();
            }
            Role::Abstain => abstain = shown,
            Role::Recheck => recheck = shown.first().cloned(),
            Role::Across => across = shown.first().cloned(),
            _ => {}
        }
    }
    let c = h.counters().await;
    let g = graded.clone().unwrap_or_default();
    let reply_notes = session.reply_notes();

    // ---- the answerable arm -------------------------------------------
    let mut fails = Vec::new();
    // (a) the summary. Three conditions, because "the value is in the
    // prompt" alone would pass on a window that never rolled.
    require(&mut fails, g.summary.is_some(), || {
        "the graded turn was shown no summary block".into()
    });
    require(&mut fails, g.prompt.contains(seed.mark), || {
        format!(
            "{:?} reached no block of the graded prompt; only the summary could carry it",
            seed.mark
        )
    });
    require(&mut fails, !g.window.contains(seed.mark), || {
        format!(
            "turn 1 is still in the window, so {:?} proves nothing",
            seed.mark
        )
    });
    // (b) the notes.
    for note in &reply_notes {
        require(&mut fails, g.guidance.iter().any(|r| r == note), || {
            format!("the reply context did not carry the note {note:?}")
        });
    }
    // (c) the knowledge update, on both sides: the store holds one current
    // version and the context shows its value, not the one it replaced.
    let current: Vec<_> = history
        .iter()
        .filter(|f| f.state == FactState::Current)
        .collect();
    require(&mut fails, current.len() == 1, || {
        format!("{} current rows for {}, want 1", current.len(), seed.key)
    });
    require(&mut fails, g.rows_for(seed.key) == 1, || {
        format!(
            "{} {} lines in the context — ghost mixing: {:?}",
            g.rows_for(seed.key),
            seed.key,
            g.facts
        )
    });
    // (d) the paraphrase. The question is asked in different words and the
    // answer still reached the model — through the fact block, not through a
    // transcript that no longer holds it.
    match g.fact_line(seed.key) {
        Some(line) => require(&mut fails, line.contains(seed.update_new), || {
            format!("{} shown as {line:?}, not {:?}", seed.key, seed.update_new)
        }),
        None => fails.push(format!("{} was not in the reply context", seed.key)),
    }
    require(&mut fails, !g.window.contains(seed.update_new), || {
        "the restated value is still in the window; this says nothing about memory".into()
    });
    // Per-ability condition.
    match seed.ability {
        "information extraction" => require(&mut fails, c.recall_calls == 1, || {
            format!(
                "{} recall calls; only the abstention turn should search",
                c.recall_calls
            )
        }),
        "multi-session reasoning" => match &across {
            Some(s) => {
                require(&mut fails, s.window.is_empty(), || {
                    format!("session two already had a window: {:?}", s.window)
                });
                require(
                    &mut fails,
                    s.fact_line(seed.key)
                        .map(|l| l.contains(seed.update_new))
                        .unwrap_or(false),
                    || format!("the fact did not cross into session two: {:?}", s.facts),
                );
            }
            None => fails.push("the second session never reached the reply model".into()),
        },
        "temporal reasoning" => {
            let want = format!(
                "{}: \"{}\" (was \"{}\" until ",
                seed.key, seed.update_new, seed.value
            );
            require(
                &mut fails,
                g.fact_line(seed.key)
                    .map(|l| l.starts_with(&want))
                    .unwrap_or(false),
                || format!("superseded value not rendered: {:?}", g.fact_line(seed.key)),
            );
        }
        "knowledge updates" => {
            let superseded: Vec<_> = history
                .iter()
                .filter(|f| f.state == FactState::Superseded)
                .collect();
            require(
                &mut fails,
                superseded.len() == 1 && superseded[0].valid_to.is_some(),
                || {
                    format!(
                        "{} superseded rows with a valid_to, want 1",
                        superseded.len()
                    )
                },
            );
        }
        "selective forgetting" => match &recheck {
            Some(s) => {
                require(&mut fails, s.fact_line(seed.key).is_none(), || {
                    format!("{} survived the forget: {:?}", seed.key, s.facts)
                });
                let after = h
                    .store()
                    .fact_history("global", seed.key)
                    .await
                    .unwrap_or_default();
                require(
                    &mut fails,
                    !after.iter().any(|f| f.state == FactState::Current),
                    || "the store still holds a current version after forget_fact".into(),
                );
            }
            None => fails.push("the turn after the forget never reached the reply model".into()),
        },
        // "abstention": its condition is the arm below, graded separately so
        // a declined answer can never be scored as a correct one.
        _ => {}
    }

    // ---- the abstention arm -------------------------------------------
    let mut declines = Vec::new();
    let first = abstain.first().cloned().unwrap_or_default();
    require(&mut declines, c.recall_calls == 1, || {
        format!(
            "{} recall calls, want the one the unanswerable turn makes",
            c.recall_calls
        )
    });
    require(&mut declines, c.recall_hits == 0, || {
        format!(
            "recall returned {} hits for something never said",
            c.recall_hits
        )
    });
    require(&mut declines, first.trace.contains("no matches"), || {
        format!(
            "the reply model was not told the search found nothing: {:?}",
            first.trace
        )
    });
    require(&mut declines, !first.shows(seed.invented), || {
        format!(
            "the context already carried {:?}; abstention is untestable here",
            seed.invented
        )
    });
    require(&mut declines, c.flags == 1, || {
        format!(
            "{} interceptor flags, want 1 for the invented value",
            c.flags
        )
    });
    require(&mut declines, abstain.len() == 2, || {
        format!(
            "{} drafts; the flagged reply was not regenerated",
            abstain.len()
        )
    });
    if let Some(second) = abstain.get(1) {
        require(
            &mut declines,
            second.do_not_state.iter().any(|s| s == seed.invented),
            || {
                format!(
                    "the regeneration was not told what to drop: {:?}",
                    second.do_not_state
                )
            },
        );
    }

    Fixture {
        id: seed.id,
        ability: seed.ability,
        lang: seed.lang,
        passed: fails.is_empty(),
        declined: declines.is_empty(),
        turns: c.turns,
        requests: c.emitter_calls + h.reply_calls(),
        replier_requests: h.reply_calls(),
        prompt_chars: g.chars(),
        summary_chars: summary_chars_of(&h, &a).await,
        summary_shown: g.summary.as_ref().map(|s| s.chars().count()).unwrap_or(0),
        notes_held: reply_notes.len(),
        notes_shown: g.guidance.len(),
        echoed: echoed_in(&h, &[&a, &b]).await,
        detail: fails.join("; "),
        abstain_detail: declines.join("; "),
    }
}

/// Every session, in seed order.
///
/// Sequential for [`crate::eval::run_all_for`]'s reason: each session builds
/// its own store and engines, so they are independent, but `requests` is a
/// reported column and a concurrent run would let the scheduler into it.
pub async fn run_all_for(run: Run) -> Vec<Fixture> {
    let mut out = Vec::new();
    for s in generate() {
        out.push(run_one(&s, run).await);
    }
    out
}

// ---------------------------------------------------------------------------
// The report
// ---------------------------------------------------------------------------

fn row_line(cells: [&str; 9]) -> String {
    format!(
        "  {:<22}  {:<24}  {:<4}  {:<6}  {:<7}  {:>7}  {:>6}  {:>5}  {:>5}\n",
        cells[0], cells[1], cells[2], cells[3], cells[4], cells[5], cells[6], cells[7], cells[8]
    )
}

/// The table, with the two arms separate and the two counts beside them.
pub fn render_table(rows: &[Fixture]) -> String {
    let mut out = String::from("\nM10 T5.1 — scripted sessions, summary and notes carried\n\n");
    out.push_str(&row_line([
        "fixture", "ability", "lang", "answer", "decline", "sum/log", "shown", "notes", "shown",
    ]));
    out.push_str(&row_line([
        "----------------------",
        "------------------------",
        "----",
        "------",
        "-------",
        "-------",
        "------",
        "-----",
        "-----",
    ]));
    for r in rows {
        out.push_str(&row_line([
            r.id,
            r.ability,
            r.lang,
            if r.passed { "ok" } else { "FAIL" },
            if r.declined { "ok" } else { "FAIL" },
            &r.summary_chars.to_string(),
            &r.summary_shown.to_string(),
            &r.notes_held.to_string(),
            &r.notes_shown.to_string(),
        ]));
    }
    let answered = rows.iter().filter(|r| r.passed).count();
    let declined = rows.iter().filter(|r| r.declined).count();
    out.push_str(&format!(
        "\n  answerable: {answered}/{} · abstention: {declined}/{} \
         (two arms, never one rate: a harness that declined everything would \
         score 0 on the first).\n",
        rows.len(),
        rows.len()
    ));
    // M12 T4.4b: per arm, so the act-or-answer arm can be set beside the
    // default one on the only column its change can move.
    out.push_str(&format!(
        "  ReplyEchoed: {} over {} sessions.\n",
        rows.iter().map(|r| r.echoed).sum::<usize>(),
        rows.len()
    ));
    let carrying = rows.iter().filter(|r| r.summary_chars > 0).count();
    let noted = rows.iter().filter(|r| r.notes_held >= 2).count();
    out.push_str(&format!(
        "  {carrying}/{} sessions hold a summary in the log; {noted}/{} hand the engine \
         at least two reply notes. A zero delta on `--ablate summary` or \
         `--ablate guidance` over this suite is insensitivity, not blindness.\n",
        rows.len(),
        rows.len()
    ));
    for r in rows.iter().filter(|r| !r.passed) {
        out.push_str(&format!("  {} ANSWER FAILED: {}\n", r.id, r.detail));
    }
    for r in rows.iter().filter(|r| !r.declined) {
        out.push_str(&format!(
            "  {} DECLINE FAILED: {}\n",
            r.id, r.abstain_detail
        ));
    }
    out
}

// ---------------------------------------------------------------------------
// Two arms side by side (M10 T5.4)
// ---------------------------------------------------------------------------

/// One ability's counts in one arm: `(ability, answered, declined, of)`.
///
/// Seed order, deduplicated by first appearance rather than sorted, so the
/// rows of two arms line up positionally the way [`crate::ablate::Report`]
/// relies on — the arms run the same `generate()` and cannot disagree about
/// which ability row three is.
pub fn per_ability(rows: &[Fixture]) -> Vec<(&'static str, usize, usize, usize)> {
    let mut out: Vec<(&'static str, usize, usize, usize)> = Vec::new();
    for r in rows {
        match out.iter_mut().find(|(a, ..)| *a == r.ability) {
            Some(cell) => {
                cell.1 += usize::from(r.passed);
                cell.2 += usize::from(r.declined);
                cell.3 += 1;
            }
            None => out.push((r.ability, usize::from(r.passed), usize::from(r.declined), 1)),
        }
    }
    out
}

/// Replier calls per fixture, summed and averaged (M10 T5.4, arm 3).
pub fn replier_requests(rows: &[Fixture]) -> (usize, f64) {
    let total: usize = rows.iter().map(|r| r.replier_requests).sum();
    let mean = if rows.is_empty() {
        0.0
    } else {
        total as f64 / rows.len() as f64
    };
    (total, mean)
}

fn arm_row(cells: [&str; 6]) -> String {
    format!(
        "  {:<24}  {:>9}  {:>9}  {:>10}  {:>10}  {:>7}\n",
        cells[0], cells[1], cells[2], cells[3], cells[4], cells[5]
    )
}

/// The two arms of one knob over the thirty sessions, per ability, both
/// graded arms, and the replier cost beside them.
///
/// One arm's per-ability rows, for a mode that runs a single weight and is
/// compared against its own earlier runs rather than against a sibling arm
/// (`ns-app eval --activation 0 | 0.5 | 1`, M10 T5.4 arm 2).
pub fn render_by_ability(label: &str, rows: &[Fixture]) -> String {
    if rows.is_empty() {
        return String::new();
    }
    let mut out = format!(
        "\nM10 T5.4 — the {} scripted sessions at {label}\n\n",
        rows.len()
    );
    out.push_str(&arm_row([
        "ability", "answer", "decline", "replier", "", "",
    ]));
    out.push_str(&arm_row([
        "------------------------",
        "---------",
        "---------",
        "----------",
        "",
        "",
    ]));
    for (a, answered, declined, of) in per_ability(rows) {
        let replier: usize = rows
            .iter()
            .filter(|r| r.ability == a)
            .map(|r| r.replier_requests)
            .sum();
        out.push_str(&arm_row([
            a,
            &format!("{answered}/{of}"),
            &format!("{declined}/{of}"),
            &replier.to_string(),
            "",
            "",
        ]));
    }
    let (total, mean) = replier_requests(rows);
    out.push_str(&arm_row([
        "ALL",
        &format!(
            "{}/{}",
            rows.iter().filter(|r| r.passed).count(),
            rows.len()
        ),
        &format!(
            "{}/{}",
            rows.iter().filter(|r| r.declined).count(),
            rows.len()
        ),
        &total.to_string(),
        "",
        "",
    ]));
    out.push_str(&format!(
        "\n  replier requests: {total} ({mean:.2}/fixture) at {label}.\n"
    ));
    out
}

/// Per ability rather than only totals because "30/30 → 30/30" is the shape
/// every one of these arms has so far, and a total that does not move cannot
/// say whether five abilities each moved by one in opposite directions.
pub fn render_arms(off_label: &str, off: &[Fixture], on_label: &str, on: &[Fixture]) -> String {
    if off.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    out.push_str(&arm_row([
        "ability",
        off_label,
        on_label,
        "decline off",
        "decline on",
        "delta",
    ]));
    out.push_str(&arm_row([
        "------------------------",
        "---------",
        "---------",
        "----------",
        "----------",
        "-------",
    ]));
    for (a, b) in per_ability(off).iter().zip(per_ability(on)) {
        out.push_str(&arm_row([
            a.0,
            &format!("{}/{}", a.1, a.3),
            &format!("{}/{}", b.1, b.3),
            &format!("{}/{}", a.2, a.3),
            &format!("{}/{}", b.2, b.3),
            &format!("{:+}", b.1 as i64 - a.1 as i64),
        ]));
    }
    let answered = |r: &[Fixture]| r.iter().filter(|x| x.passed).count();
    let declined = |r: &[Fixture]| r.iter().filter(|x| x.declined).count();
    let (off_total, off_mean) = replier_requests(off);
    let (on_total, on_mean) = replier_requests(on);
    out.push_str(&arm_row([
        "ALL",
        &format!("{}/{}", answered(off), off.len()),
        &format!("{}/{}", answered(on), on.len()),
        &format!("{}/{}", declined(off), off.len()),
        &format!("{}/{}", declined(on), on.len()),
        &format!("{:+}", answered(on) as i64 - answered(off) as i64),
    ]));
    out.push_str(&format!(
        "\n  replier requests: {off_total} ({off_mean:.2}/fixture) {off_label} → \
         {on_total} ({on_mean:.2}/fixture) {on_label} ({:+}).\n",
        on_total as i64 - off_total as i64
    ));
    out
}

// ---------------------------------------------------------------------------
// The seeds
// ---------------------------------------------------------------------------

/// Thirty sessions, five per memory ability, cs and en.
///
/// Small enough that a person can read the whole table in one sitting and
/// disagree with a case — `paraphrase.rs`'s argument for twelve cases, at the
/// size the plan's exit criterion asks for.
pub fn seeds() -> &'static [Seed] {
    &SEEDS
}

const SEEDS: [Seed; 30] = [
    // --- information extraction ---------------------------------------
    Seed {
        id: "ie/en/name",
        ability: "information extraction",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "we are exhibiting at the Brumlov trade fair this spring",
        mark: "Brumlov",
        said: "my name is Martin",
        key: "user.name",
        value: "Martin",
        updated: "actually everyone calls me Marek",
        update_new: "Marek",
        ask: "remind me who I am",
        note: "Keep answers to one sentence.",
        unanswerable: "how much bitcoin do I hold?",
        recall_query: "bitcoin",
        invented: "Helsinki",
        invented_draft: "Your bitcoin sits in Helsinki.",
    },
    Seed {
        id: "ie/cs/jmeno",
        ability: "information extraction",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "na jaře vystavujeme na veletrhu v Kroměříži",
        mark: "Kroměříži",
        said: "jmenuji se Jana",
        key: "user.name",
        value: "Jana",
        updated: "vlastně mi říkejte Janička",
        update_new: "Janička",
        ask: "připomeň mi, kdo jsem",
        note: "Odpovídej česky a krátce.",
        unanswerable: "kolik mám kryptoměn?",
        recall_query: "kryptoměn",
        invented: "Helsinkách",
        invented_draft: "Máš je v Helsinkách.",
    },
    Seed {
        id: "ie/en/age",
        ability: "information extraction",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the new guillotine arrived from Reichenbach last week",
        mark: "Reichenbach",
        said: "I am 34",
        key: "user.age",
        value: "34",
        updated: "I turned 35 yesterday",
        update_new: "35",
        ask: "how many years have I been around",
        note: "State ages as plain numbers.",
        unanswerable: "what is my sailing licence number?",
        recall_query: "sailing",
        invented: "Trieste",
        invented_draft: "Your licence was issued in Trieste.",
    },
    Seed {
        id: "ie/cs/format",
        ability: "information extraction",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "objednali jsme nový řezací stroj značky Perfecta",
        mark: "Perfecta",
        said: "piš mi časy ve dvacetičtyřhodinovém formátu",
        key: "user.preference.time_format",
        value: "24-hodinovy",
        updated: "radši mi je piš i se sekundami",
        update_new: "24-hodinovy se sekundami",
        ask: "jak mám zapisovat hodiny",
        note: "Uživatel nechce dopoledne ani odpoledne.",
        unanswerable: "kolik mám najetých kilometrů na kole?",
        recall_query: "kilometrů",
        invented: "Znojma",
        invented_draft: "Jel jsi do Znojma.",
    },
    Seed {
        id: "ie/en/workshop",
        ability: "information extraction",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Vogel account is our biggest this quarter",
        mark: "Vogel",
        said: "my workshop is on Bezrucova street",
        key: "user.workshop",
        value: "Bezrucova",
        updated: "we moved the workshop to Slezska",
        update_new: "Slezska",
        ask: "where do I do the actual work",
        note: "Answer address questions with the street name only.",
        unanswerable: "what is my scuba certification level?",
        recall_query: "scuba",
        invented: "Dahab",
        invented_draft: "You certified in Dahab.",
    },
    // --- multi-session reasoning ---------------------------------------
    Seed {
        id: "ms/en/budget",
        ability: "multi-session reasoning",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Halden order came in on Tuesday",
        mark: "Halden",
        said: "our budget for the campaign is 2000 crowns",
        key: "user.budget.total",
        value: "2000 crowns",
        updated: "the budget went up to 2600 crowns",
        update_new: "2600 crowns",
        ask: "how much money are we allowed to spend",
        note: "Amounts always in crowns.",
        unanswerable: "what did the notary say?",
        recall_query: "notary",
        invented: "Uppsala",
        invented_draft: "The notary wrote from Uppsala.",
    },
    Seed {
        id: "ms/cs/rozpocet",
        ability: "multi-session reasoning",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "zakázka pro Hrádek přišla v úterý",
        mark: "Hrádek",
        said: "náš rozpočet na kampaň je 2000 korun",
        key: "user.rozpocet",
        value: "2000 korun",
        updated: "zvedli jsme to na 2600 korun",
        update_new: "2600 korun",
        ask: "kolik peněz můžeme utratit",
        note: "Částky uváděj v korunách.",
        unanswerable: "co říkal notář?",
        recall_query: "notář",
        invented: "Uppsale",
        invented_draft: "Notář psal z Uppsale.",
    },
    Seed {
        id: "ms/en/deadline",
        ability: "multi-session reasoning",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Kessler proofs are still with the client",
        mark: "Kessler",
        said: "everything has to be finished before the fair on the twelfth",
        key: "user.deadline",
        value: "the twelfth",
        updated: "it moved to the fifteenth",
        update_new: "the fifteenth",
        ask: "what is the last possible day for this work",
        note: "Dates as the user said them.",
        unanswerable: "who won the regatta?",
        recall_query: "regatta",
        invented: "Lisbon",
        invented_draft: "The regatta went to Lisbon.",
    },
    Seed {
        id: "ms/cs/termin",
        ability: "multi-session reasoning",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "korektury pro Kesslera jsou pořád u klienta",
        mark: "Kesslera",
        said: "všechno musí být hotové před veletrhem dvanáctého",
        key: "user.termin",
        value: "dvanáctého",
        updated: "posunulo se to na patnáctého",
        update_new: "patnáctého",
        ask: "dokdy nejpozději to má být udělané",
        note: "Termíny uváděj tak, jak je řekl uživatel.",
        unanswerable: "kdo vyhrál tu regatu?",
        recall_query: "regatu",
        invented: "Lisabonu",
        invented_draft: "Vyhráli ji v Lisabonu.",
    },
    Seed {
        id: "ms/en/supplier",
        ability: "multi-session reasoning",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Wolseley paper is out of stock again",
        mark: "Wolseley",
        said: "we order the card stock from Papirna",
        key: "user.supplier",
        value: "Papirna",
        updated: "we switched to Grafix",
        update_new: "Grafix",
        ask: "who sells us the thick sheets",
        note: "Name the current supplier only.",
        unanswerable: "what did the kennel say about the dog?",
        recall_query: "kennel",
        invented: "Ostend",
        invented_draft: "The kennel called from Ostend.",
    },
    // --- temporal reasoning ---------------------------------------------
    Seed {
        id: "tr/en/name",
        ability: "temporal reasoning",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Aldersgate invoices are printed",
        mark: "Aldersgate",
        said: "my name is Petra",
        key: "user.name",
        value: "Petra",
        updated: "call me Radka from now on",
        update_new: "Radka",
        ask: "what was I called before",
        note: "Say the old name and when it changed.",
        unanswerable: "what is my chess rating?",
        recall_query: "chess",
        invented: "Reykjavik",
        invented_draft: "Your rating came from Reykjavik.",
    },
    Seed {
        id: "tr/cs/jmeno",
        ability: "temporal reasoning",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "faktury pro Albrechtice jsou vytištěné",
        mark: "Albrechtice",
        said: "jmenuji se Petra",
        key: "user.name",
        value: "Petra",
        updated: "říkejte mi Radka",
        update_new: "Radka",
        ask: "jak jsem se jmenovala dřív",
        note: "Uveď staré jméno a kdy se změnilo.",
        unanswerable: "jaké mám šachové ELO?",
        recall_query: "šachové",
        invented: "Reykjavíku",
        invented_draft: "Pochází z Reykjavíku.",
    },
    Seed {
        id: "tr/en/city",
        ability: "temporal reasoning",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Thorvald machine needs a service",
        mark: "Thorvald",
        said: "I live in Olomouc",
        key: "user.city",
        value: "Olomouc",
        updated: "I moved to Zlin last month",
        update_new: "Zlin",
        ask: "where did I used to be based",
        note: "Mention the previous city when the user asks about before.",
        unanswerable: "what is my diving depth record?",
        recall_query: "diving",
        invented: "Sharm",
        invented_draft: "Your record is from Sharm.",
    },
    Seed {
        id: "tr/cs/mesto",
        ability: "temporal reasoning",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "stroj značky Wanderer potřebuje servis",
        mark: "Wanderer",
        said: "bydlím v Olomouci",
        key: "user.city",
        value: "Olomouci",
        updated: "přestěhoval jsem se do Zlína",
        update_new: "Zlína",
        ask: "kde jsem byl předtím",
        note: "Zmiň předchozí město, když se ptám na dřív.",
        unanswerable: "jaký mám rekord v potápění?",
        recall_query: "potápění",
        invented: "Sharmu",
        invented_draft: "Rekord je ze Sharmu.",
    },
    Seed {
        id: "tr/en/role",
        ability: "temporal reasoning",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Lindqvist contract runs to December",
        mark: "Lindqvist",
        said: "I am the shift foreman",
        key: "user.role",
        value: "shift foreman",
        updated: "they promoted me to plant manager",
        update_new: "plant manager",
        ask: "what was my job title earlier",
        note: "Give the current title first, then the old one.",
        unanswerable: "when is my pilot medical due?",
        recall_query: "pilot",
        invented: "Kiruna",
        invented_draft: "It was done in Kiruna.",
    },
    // --- knowledge updates ----------------------------------------------
    Seed {
        id: "ku/en/age",
        ability: "knowledge updates",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Ravensburg reprint went out yesterday",
        mark: "Ravensburg",
        said: "I am 17",
        key: "user.age",
        value: "17",
        updated: "wait, actually I am 18 now",
        update_new: "18",
        ask: "how old does that make me",
        note: "Ages are plain numbers.",
        unanswerable: "what is my library card number?",
        recall_query: "library",
        invented: "Turku",
        invented_draft: "Your card is from Turku.",
    },
    Seed {
        id: "ku/cs/vek",
        ability: "knowledge updates",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "dotisk pro Ravensburg šel včera ven",
        mark: "Ravensburg",
        said: "je mi sedmnáct",
        key: "user.age",
        value: "sedmnáct",
        updated: "vlastně už mi je osmnáct",
        update_new: "osmnáct",
        ask: "kolik mi je let",
        note: "Věk uváděj slovem, jak ho řekl uživatel.",
        unanswerable: "jaké mám číslo čtenářského průkazu?",
        recall_query: "průkazu",
        invented: "Turku",
        invented_draft: "Průkaz je z Turku.",
    },
    Seed {
        id: "ku/en/phone",
        ability: "knowledge updates",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Ashby quote is still open",
        mark: "Ashby",
        said: "my number is 776 112 998",
        key: "user.phone",
        value: "776 112 998",
        updated: "the new one is 604 330 221",
        update_new: "604 330 221",
        ask: "what do you ring me on",
        note: "Give digits in groups of three.",
        unanswerable: "what is my insurance policy id?",
        recall_query: "insurance",
        invented: "Galway",
        invented_draft: "Your policy came from Galway.",
    },
    Seed {
        id: "ku/cs/email",
        ability: "knowledge updates",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "nabídka pro Ashbyho je pořád otevřená",
        mark: "Ashbyho",
        said: "můj e-mail je jana@tiskarna.cz",
        key: "user.email",
        value: "jana@tiskarna.cz",
        updated: "nový je jana@studio.cz",
        update_new: "jana@studio.cz",
        ask: "kam ti mám psát",
        note: "E-mail uváděj celý.",
        unanswerable: "jaké mám číslo pojistky?",
        recall_query: "pojistky",
        invented: "Galway",
        invented_draft: "Pojistka je z Galway.",
    },
    Seed {
        id: "ku/en/paper",
        ability: "knowledge updates",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Kolding sample book arrived",
        mark: "Kolding",
        said: "we print the flyers on 150 gram paper",
        key: "user.paper.weight",
        value: "150 gram",
        updated: "we changed them to 170 gram",
        update_new: "170 gram",
        ask: "how heavy is the stock we use",
        note: "Paper weights in grams.",
        unanswerable: "what did the dentist recommend?",
        recall_query: "dentist",
        invented: "Poznan",
        invented_draft: "The dentist wrote from Poznan.",
    },
    // --- abstention ------------------------------------------------------
    Seed {
        id: "ab/en/email",
        ability: "abstention",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Mardall job is on hold",
        mark: "Mardall",
        said: "I prefer plain text emails",
        key: "user.preference.email",
        value: "plain text",
        updated: "actually send me html now",
        update_new: "html",
        ask: "how should you write to me",
        note: "Never guess a value the context does not carry.",
        unanswerable: "which airline do I fly with?",
        recall_query: "airline",
        invented: "Lufthansa",
        invented_draft: "You fly Lufthansa.",
    },
    Seed {
        id: "ab/cs/email",
        ability: "abstention",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "zakázka Mardall je pozastavená",
        mark: "Mardall",
        said: "chci e-maily v prostém textu",
        key: "user.preference.email",
        value: "prosty text",
        updated: "teď mi posílej html",
        update_new: "html",
        ask: "jak mi máš psát",
        note: "Nikdy nehádej hodnotu, kterou kontext nenese.",
        unanswerable: "kterou aerolinkou létám?",
        recall_query: "aerolinkou",
        invented: "Lufthansou",
        invented_draft: "Létáš s Lufthansou.",
    },
    Seed {
        id: "ab/en/hours",
        ability: "abstention",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Perrin folder is empty",
        mark: "Perrin",
        said: "the shop closes at six",
        key: "user.shop.closes",
        value: "six",
        updated: "we close at seven from Monday",
        update_new: "seven",
        ask: "when do we lock up",
        note: "Do not invent opening hours.",
        unanswerable: "what is my blood type?",
        recall_query: "blood",
        invented: "Reims",
        invented_draft: "Your record came from Reims.",
    },
    Seed {
        id: "ab/cs/hodiny",
        ability: "abstention",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "složka Perrin je prázdná",
        mark: "Perrin",
        said: "tiskárna zavírá v šest",
        key: "user.zavirame",
        value: "šest",
        updated: "od pondělí zavíráme v sedm",
        update_new: "sedm",
        ask: "kdy zamykáme",
        note: "Otevírací dobu si nevymýšlej.",
        unanswerable: "jakou mám krevní skupinu?",
        recall_query: "krevní",
        invented: "Remeše",
        invented_draft: "Záznam je z Remeše.",
    },
    Seed {
        id: "ab/en/van",
        ability: "abstention",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Hollis estimate needs a signature",
        mark: "Hollis",
        said: "the van is a white transit",
        key: "user.van",
        value: "white transit",
        updated: "it is a blue sprinter now",
        update_new: "blue sprinter",
        ask: "what do we drive",
        note: "Only describe the vehicle the context names.",
        unanswerable: "what is my parking permit zone?",
        recall_query: "parking",
        invented: "Bergen",
        invented_draft: "Your permit is for Bergen.",
    },
    // --- selective forgetting -------------------------------------------
    Seed {
        id: "sf/en/pin",
        ability: "selective forgetting",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Nordahl pallets are in the yard",
        mark: "Nordahl",
        said: "my card pin is 4471",
        key: "user.card.pin",
        value: "4471",
        updated: "the pin is 8802 now",
        update_new: "8802",
        ask: "what do I punch in at the terminal",
        note: "Forget a secret the moment the user asks.",
        unanswerable: "what is my passport expiry?",
        recall_query: "passport",
        invented: "Gdansk",
        invented_draft: "It was issued in Gdansk.",
    },
    Seed {
        id: "sf/cs/pin",
        ability: "selective forgetting",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "palety Nordahl jsou na dvoře",
        mark: "Nordahl",
        said: "můj pin je 4471",
        key: "user.card.pin",
        value: "4471",
        updated: "teď je to 8802",
        update_new: "8802",
        ask: "co mám ťukat na terminálu",
        note: "Tajemství zapomeň hned, jak o to požádám.",
        unanswerable: "kdy mi končí cestovní pas?",
        recall_query: "cestovní",
        invented: "Gdaňsku",
        invented_draft: "Vydali ho v Gdaňsku.",
    },
    Seed {
        id: "sf/en/post",
        ability: "selective forgetting",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Yarrow delivery slipped a day",
        mark: "Yarrow",
        said: "send post to Havlickova 12",
        key: "user.post",
        value: "Havlickova 12",
        updated: "it goes to Krizova 4 now",
        update_new: "Krizova 4",
        ask: "where does my mail land",
        note: "Drop an address on request.",
        unanswerable: "what is my gym locker code?",
        recall_query: "locker",
        invented: "Tromso",
        invented_draft: "Your locker is in Tromso.",
    },
    Seed {
        id: "sf/cs/posta",
        ability: "selective forgetting",
        lang: "cs",
        persona: "Jsi stručný asistent pro malou tiskárnu.",
        opening: "dodávka Yarrow se opozdila o den",
        mark: "Yarrow",
        said: "poštu posílej na Havlíčkovu 12",
        key: "user.post",
        value: "Havlíčkovu 12",
        updated: "teď chodí na Křížovou 4",
        update_new: "Křížovou 4",
        ask: "kam mi chodí dopisy",
        note: "Adresu na požádání smaž.",
        unanswerable: "jaký mám kód od skříňky v posilovně?",
        recall_query: "posilovně",
        invented: "Tromsu",
        invented_draft: "Skříňka je v Tromsu.",
    },
    Seed {
        id: "sf/en/signoff",
        ability: "selective forgetting",
        lang: "en",
        persona: "You are a terse assistant for a small print shop.",
        opening: "the Quint folder was archived",
        mark: "Quint",
        said: "my sign-off is MK",
        key: "user.signoff",
        value: "MK",
        updated: "sign off as MKN from now",
        update_new: "MKN",
        ask: "what initials go at the bottom",
        note: "Use the shortest current sign-off.",
        unanswerable: "what is my ham radio callsign?",
        recall_query: "callsign",
        invented: "Faroe",
        invented_draft: "It came from Faroe.",
    },
];

/// M12 T4.4b. The act-or-answer arm's own fixture: a chat-tier turn whose
/// one emitter call answers, graded on the two things the arm claims — the
/// user is told what the emitter said, and the replier never ran.
///
/// Outside the thirty-session table on purpose. Those sessions are a fixed
/// twelve-turn shape over six memory abilities, with five seeds each; a
/// thirty-first row would move every per-ability count and grade a claim
/// none of the six is about. This is the arm's claim, run against the same
/// harness.
pub async fn answering_chat_turn(run: Run) -> (String, usize) {
    let h = Harness::routed_for_run(Run {
        act_or_answer: true,
        ..run
    });
    let sid = SessionId("fx-act-or-answer".into());
    let answer = "Je deset čtyřicet jedna.";
    let shown = h
        .turn_answering(
            &sid,
            // A plain conversational message: no cue the router reads as a
            // task, so the turn routes to Chat and the path is reachable.
            "ahoj, jak se máš?",
            vec![nscore::Emission {
                proposal: Proposal {
                    rationale: format!("{} {answer}", nscore::ANSWERED_IN_EMITTER_PREFIX),
                    action: "respond_directly".into(),
                    args: serde_json::json!({}),
                },
                answer: Some(answer.into()),
                say: None,
            }],
        )
        .await;
    let replied = h
        .store()
        .load(&sid)
        .await
        .unwrap_or_default()
        .iter()
        .find_map(|e| match &e.kind {
            EventKind::Replied { text } => Some(text.clone()),
            _ => None,
        })
        .unwrap_or_default();
    (replied, shown.len())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::paraphrase::overlap;

    /// M12 T4.4b. The arm's grader: the reply is the emitter's answer, and
    /// the replier — the `Probe` that records every context it is shown —
    /// was never called, which is the request the arm saves.
    #[tokio::test]
    async fn an_answering_chat_turn_replies_without_the_replier() {
        let (reply, replier_calls) = answering_chat_turn(Run::default()).await;
        assert_eq!(reply, "Je deset čtyřicet jedna.");
        assert_eq!(replier_calls, 0, "the replier drafted after all");

        // And with the knob off the same script costs the replier call: the
        // fixture is measuring the knob, not the double.
        let h = Harness::routed_for_run(Run::default());
        let sid = SessionId("fx-act-or-answer-off".into());
        let shown = h
            .turn_answering(
                &sid,
                "ahoj, jak se máš?",
                vec![nscore::Emission {
                    proposal: Proposal {
                        rationale: "answered".into(),
                        action: "respond_directly".into(),
                        args: serde_json::json!({}),
                    },
                    answer: Some("Je deset čtyřicet jedna.".into()),
                    say: None,
                }],
            )
            .await;
        assert_eq!(shown.len(), 1, "the replier was skipped with the knob off");
    }

    /// The plan's own risk line — *"fixtures generated by a model leak the
    /// model's style"* — answered the way it wrote: a seed a person authored,
    /// a pure expansion, and a regeneration that is byte-identical.
    ///
    /// Rendered rather than structural: `Vec<Session>` equality would pass on
    /// two values whose printed form differed, and the printed form is what a
    /// reviewer reads.
    #[test]
    fn fixtures_regenerate_byte_identically() {
        let first = render_corpus();
        let second = render_corpus();
        assert_eq!(first, second, "the corpus is not reproducible");
        // And it is not vacuous: every seed has to be in it, with its notes
        // and its two graded turns.
        for seed in seeds() {
            assert!(
                first.contains(seed.id),
                "{} missing from the corpus",
                seed.id
            );
            assert!(first.contains(seed.ask), "{}: no graded turn", seed.id);
            assert!(
                first.contains(seed.unanswerable),
                "{}: no unanswerable turn",
                seed.id
            );
        }
        assert!(first.contains(GLOBAL_NOTE));
    }

    /// The exit criterion, counted rather than asserted about one fixture.
    #[test]
    fn every_memory_ability_has_at_least_five_sessions() {
        for ability in MEMORY_ABILITIES {
            let n = seeds().iter().filter(|s| s.ability == ability).count();
            assert!(n >= 5, "{ability}: {n} sessions, want at least 5");
        }
        // And no seed names an ability the suite does not report.
        for seed in seeds() {
            assert!(
                MEMORY_ABILITIES.contains(&seed.ability),
                "{}: {:?} is not one of the six",
                seed.id,
                seed.ability
            );
        }
        assert_eq!(seeds().len(), 30);
    }

    /// The corpus's honesty checks, `paraphrase.rs`'s in this module's terms.
    ///
    /// A "paraphrase" that reused the statement's vocabulary would make (d)
    /// pass by construction; a `mark` that appeared in a filler line or in the
    /// question would make (a) pass through the window instead of through the
    /// summary. Either would be a fixture that measured nothing, so either
    /// breaks the build.
    #[test]
    fn every_graded_question_is_a_paraphrase_and_every_mark_is_unique_to_turn_one() {
        for (n, seed) in seeds().iter().enumerate() {
            let o = overlap(seed.ask, seed.said);
            assert!(
                o <= 0.30,
                "{}: the question shares {:.0}% of its tokens with the statement — that is \
                 a rewording, not a paraphrase",
                seed.id,
                o * 100.0
            );
            assert!(
                seed.opening.contains(seed.mark),
                "{}: the mark is not in the opening",
                seed.id
            );
            let elsewhere = [
                seed.said,
                seed.updated,
                seed.ask,
                seed.unanswerable,
                seed.note,
                seed.persona,
                seed.value,
                seed.update_new,
            ];
            for text in elsewhere {
                assert!(
                    !text.contains(seed.mark),
                    "{}: {:?} also carries the mark, so the summary is not its only route",
                    seed.id,
                    text
                );
            }
            for f in filler(seed.lang, n) {
                assert!(
                    !f.contains(seed.mark),
                    "{}: a filler line carries the mark",
                    seed.id
                );
            }
            assert_ne!(
                seed.value, seed.update_new,
                "{}: the update updates nothing",
                seed.id
            );
            assert!(
                seed.unanswerable.contains(seed.recall_query),
                "{}: the recall query is not a span of the user's own words",
                seed.id
            );
            assert!(
                seed.invented_draft.contains(seed.invented),
                "{}: the draft does not state the invented value",
                seed.id
            );
            assert!(
                seed.key.starts_with("user."),
                "{}: the graded key has to be pinned, or the arm measures retrieval",
                seed.id
            );
        }
        // Ids are the fixture column and the ledger key; two the same would
        // silently halve the suite.
        let mut ids: Vec<&str> = seeds().iter().map(|s| s.id).collect();
        ids.sort_unstable();
        let before = ids.len();
        ids.dedup();
        assert_eq!(ids.len(), before, "duplicate seed id");
    }

    /// The whole suite, whole arm, and the two counts that make a delta
    /// readable. Slow (thirty sessions of a dozen turns each) and worth it:
    /// it is the only test that proves the sessions really carry what the
    /// seeds say they carry.
    #[tokio::test]
    async fn the_full_arm_answers_and_declines_on_every_fixture() {
        let rows = run_all_for(Run::default()).await;
        println!("{}", render_table(&rows));
        assert_eq!(rows.len(), 30);
        assert!(
            rows.iter().all(|r| r.passed),
            "the full arm must be green or every delta means nothing"
        );
        assert!(
            rows.iter().all(|r| r.declined),
            "an unanswerable item that was not declined"
        );
        // The claim the ablation arms rest on.
        assert!(
            rows.iter()
                .all(|r| r.summary_chars > 0 && r.summary_shown > 0),
            "a session that carries no summary cannot say anything about `--ablate summary`"
        );
        assert!(
            rows.iter().all(|r| r.notes_held >= 2 && r.notes_shown >= 2),
            "a session with fewer than two rendered notes cannot say anything about \
             `--ablate guidance`"
        );
    }

    /// M10 T5.4, arm 2: the half of the activation reading that is not the
    /// tie corpus.
    ///
    /// `ties.rs` proves the weight *moves* something (0/8 → 8/8). This
    /// proves it breaks nothing, which is the other half of the M9 rule —
    /// a knob moves off its default only on a **non-regressing** verbatim
    /// arm, and "non-regressing" is measured here, not there. `w = 1`
    /// because that is the value the tie corpus argues for; a run at 0.5
    /// that regressed while 1 held would be a stranger finding than either.
    #[tokio::test]
    async fn the_thirty_sessions_do_not_regress_at_activation_weight_one() {
        let base = run_all_for(Run::default()).await;
        let hot = run_all_for(Run {
            activation_weight: 1.0,
            ..Run::default()
        })
        .await;
        let table = render_arms("w = 0", &base, "w = 1", &hot);
        let answered = |r: &[Fixture]| r.iter().filter(|x| x.passed).count();
        let declined = |r: &[Fixture]| r.iter().filter(|x| x.declined).count();
        assert_eq!(answered(&base), 30, "{table}");
        assert!(answered(&hot) >= answered(&base), "{table}");
        assert!(declined(&hot) >= declined(&base), "{table}");
        // And the arms are comparable row for row, which is what lets the
        // per-ability table be read positionally.
        assert_eq!(
            base.iter().map(|r| r.id).collect::<Vec<_>>(),
            hot.iter().map(|r| r.id).collect::<Vec<_>>()
        );
        assert!(table.contains("w = 1"), "{table}");
        assert!(table.contains("replier requests:"), "{table}");
    }

    /// The single-arm rendering the `--activation` sweep prints, and the
    /// replier column it exists to carry.
    #[tokio::test]
    async fn the_single_arm_table_names_every_ability_and_its_replier_cost() {
        let rows = run_all_for(Run::default()).await;
        let t = render_by_ability("w = 0", &rows);
        for (ability, answered, declined, of) in per_ability(&rows) {
            assert_eq!(of, 5, "{ability} has {of} sessions, want 5");
            assert_eq!((answered, declined), (5, 5), "{ability}:\n{t}");
            assert!(t.contains(ability), "{t}");
        }
        let (total, mean) = replier_requests(&rows);
        assert!(total > 0 && mean > 0.0, "{t}");
        assert!(t.contains(&format!("{total} ({mean:.2}/fixture)")), "{t}");
    }
}
